### ISSUE TITLE
LSP Spyglass crashes after opening any ".mcfunction" files

### ISSUE THREAD

**Issue by benazarenko** [SpyglassMC/Spyglass#1066]
The title says it all. I installed exactly as written in the instruction.
The code snippets work fine so I don't know what's wrong with it. The only thing I did is I changed server to server.js, because Node.js doesn't support extensionless files.
Sublime Text Build 4143
(not sure if it's the right place to ask, but spyglassmc.com provides this link for issues)

```
:: [16:17:27.559] --> LSP-Spyglass initialize (1): {'initializationOptions': {}, 'rootPath': 'C:\\Users\\benaz\\Downloads\\fafik77 RNG', 'capabilities': {'textDocument': {'formatting': {'dynamicRegistration': True}, 'callHierarchy': {'dynamicRegistration': True}, 'codeAction': {'resolveSupport': {'properties': ['edit']}, 'isPreferredSupport': True, 'codeActionLiteralSupport': {'codeActionKind': {'valueSet': ['quickfix', 'refactor', 'refactor.extract', 'refactor.inline', 'refactor.rewrite', 'source.fixAll', 'source.organizeImports']}}, 'dataSupport': True, 'dynamicRegistration': True}, 'rename': {'prepareSupportDefaultBehavior': 1, 'prepareSupport': True, 'dynamicRegistration': True}, 'declaration': {'linkSupport': True, 'dynamicRegistration': True}, 'documentLink': {'tooltipSupport': True, 'dynamicRegistration': True}, 'rangeFormatting': {'dynamicRegistration': True}, 'documentSymbol': {'symbolKind': {'valueSet': [18, 24, 2, 26, 14, 23, 4, 19, 3, 16, 12, 5, 11, 13, 22, 21, 8, 17, 15, 20, 9, 25, 10, 7, 1, 6]}, 'tagSupport': {'valueSet': [1]}, 'hierarchicalDocumentSymbolSupport': True, 'dynamicRegistration': True}, 'selectionRange': {'dynamicRegistration': True}, 'completion': {'completionList': {'itemDefaults': ['editRange', 'insertTextFormat', 'data']}, 'completionItem': {'documentationFormat': ['markdown', 'plaintext'], 'labelDetailsSupport': True, 'insertTextModeSupport': {'valueSet': [2]}, 'insertReplaceSupport': True, 'resolveSupport': {'properties': ['detail', 'documentation', 'additionalTextEdits']}, 'deprecatedSupport': True, 'snippetSupport': True, 'tagSupport': {'valueSet': [1]}}, 'completionItemKind': {'valueSet': [1, 19, 23, 9, 15, 13, 21, 22, 14, 2, 12, 3, 18, 7, 8, 16, 11, 5, 6, 4, 24, 25, 10, 20, 17]}, 'insertTextMode': 2, 'dynamicRegistration': True}, 'typeDefinition': {'linkSupport': True, 'dynamicRegistration': True}, 'colorProvider': {'dynamicRegistration': True}, 'definition': {'linkSupport': True, 'dynamicRegistration': True}, 'synchronization': {'didSave': True, 'willSave': True, 'willSaveWaitUntil': True, 'dynamicRegistration': True}, 'references': {'dynamicRegistration': True}, 'implementation': {'linkSupport': True, 'dynamicRegistration': True}, 'semanticTokens': {'requests': {'range': True, 'full': {'delta': True}}, 'tokenModifiers': ['modification', 'deprecated', 'abstract', 'static', 'defaultLibrary', 'async', 'documentation', 'definition', 'readonly', 'declaration'], 'overlappingTokenSupport': False, 'dynamicRegistration': True, 'multilineTokenSupport': True, 'augmentsSyntaxTokens': True, 'tokenTypes': ['variable', 'event', 'typeParameter', 'struct', 'keyword', 'function', 'property', 'type', 'method', 'comment', 'enum', 'interface', 'macro', 'class', 'decorator', 'regexp', 'namespace', 'string', 'operator', 'modifier', 'parameter', 'enumMember', 'number'], 'formats': ['relative']}, 'typeHierarchy': {'dynamicRegistration': True}, 'signatureHelp': {'signatureInformation': {'documentationFormat': ['markdown', 'plaintext'], 'parameterInformation': {'labelOffsetSupport': True}, 'activeParameterSupport': True}, 'contextSupport': True, 'dynamicRegistration': True}, 'diagnostic': {'relatedDocumentSupport': True, 'dynamicRegistration': True}, 'publishDiagnostics': {'versionSupport': True, 'codeDescriptionSupport': True, 'tagSupport': {'valueSet': [2, 1]}, 'dataSupport': True, 'relatedInformation': True}, 'documentHighlight': {'dynamicRegistration': True}, 'hover': {'contentFormat': ['markdown', 'plaintext'], 'dynamicRegistration': True}, 'inlayHint': {'resolveSupport': {'properties': ['textEdits', 'label.command']}, 'dynamicRegistration': True}, 'codeLens': {'dynamicRegistration': True}}, 'window': {'showMessage': {'messageActionItem': {'additionalPropertiesSupport': True}}, 'showDocument': {'support': True}, 'workDoneProgress': True}, 'workspace': {'applyEdit': True, 'executeCommand': {}, 'configuration': True, 'semanticTokens': {'refreshSupport': True}, 'diagnostics': {'refreshSupport': True}, 'workspaceEdit': {'failureHandling': 'abort', 'documentChanges': True}, 'didChangeConfiguration': {'dynamicRegistration': True}, 'inlayHint': {'refreshSupport': True}, 'symbol': {'symbolKind': {'valueSet': [18, 24, 2, 26, 14, 23, 4, 19, 3, 16, 12, 5, 11, 13, 22, 21, 8, 17, 15, 20, 9, 25, 10, 7, 1, 6]}, 'tagSupport': {'valueSet': [1]}, 'dynamicRegistration': True}, 'workspaceFolders': True, 'codeLens': {'refreshSupport': True}}, 'general': {'markdown': {'version': '3.2.2', 'parser': 'Python-Markdown'}, 'regularExpressions': {'engine': 'ECMAScript'}}}, 'rootUri': 'file:///C:/Users/benaz/Downloads/fafik77%20RNG', 'processId': 7316, 'clientInfo': {'version': '1.24.0', 'name': 'Sublime Text LSP'}, 'workspaceFolders': [{'name': 'fafik77 RNG', 'uri': 'file:///C:/Users/benaz/Downloads/fafik77%20RNG'}, {'name': 'testpack', 'uri': 'file:///C:/Users/benaz/AppData/Roaming/.tlauncher/legacy/Minecraft/game/home/Fabric-1.19/saves/datatest/datapacks/testpack'}]}
LSP-Spyglass: [onInitialize] processId = 7316
LSP-Spyglass: [onInitialize] clientInfo = {"version":"1.24.0","name":"Sublime Text LSP"}
:: [16:17:28.926] <-  LSP-Spyglass window/logMessage: {'message': '[onInitialize] processId = 7316', 'type': 3}
:: [16:17:28.927] <-  LSP-Spyglass window/logMessage: {'message': '[onInitialize] clientInfo = {"version":"1.24.0","name":"Sublime Text LSP"}', 'type': 3}
LSP-Spyglass: [onInitialize] initializationOptions = {}
LSP-Spyglass: [Project] [init] cacheRoot = “file:///C:/Users/benaz/AppData/Local/spyglassmc-nodejs/Cache/”
LSP-Spyglass: [CacheService#load] symbolCachePath = “file:///C:/Users/benaz/AppData/Local/spyglassmc-nodejs/Cache/symbols/2a457a18f03b2a617add1ee4ca994897fe084e31.json.gz”
:: [16:17:28.928] <-  LSP-Spyglass window/logMessage: {'message': '[onInitialize] initializationOptions = {}', 'type': 3}
:: [16:17:28.928] <-  LSP-Spyglass window/logMessage: {'message': '[Project] [init] cacheRoot = “file:///C:/Users/benaz/AppData/Local/spyglassmc-nodejs/Cache/”', 'type': 3}
:: [16:17:28.928] <-  LSP-Spyglass window/logMessage: {'message': '[CacheService#load] symbolCachePath = “file:///C:/Users/benaz/AppData/Local/spyglassmc-nodejs/Cache/symbols/2a457a18f03b2a617add1ee4ca994897fe084e31.json.gz”', 'type': 3}
LSP-Spyglass: [Profiler: cache#load] Done: Read File in 7.148699998855591 ms
LSP-Spyglass: [Profiler: cache#load] Done: Link Symbols in 0.49970000982284546 ms
LSP-Spyglass: [Profiler: cache#load] == Summary ==
LSP-Spyglass: [Profiler: cache#load] Read File    - 7.148699998855591 ms
LSP-Spyglass: [Profiler: cache#load] Link Symbols - 0.49970000982284546 ms
LSP-Spyglass: [Profiler: cache#load] Total        - 7.648400008678436 ms
:: [16:17:28.934] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: cache#load] Done: Read File in 7.148699998855591 ms', 'type': 3}
:: [16:17:28.934] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: cache#load] Done: Link Symbols in 0.49970000982284546 ms', 'type': 3}
LSP-Spyglass: [Profiler: project#init] Done: Load Cache in 8.92059999704361 ms
:: [16:17:28.934] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: cache#load] == Summary ==', 'type': 3}
:: [16:17:28.935] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: cache#load] Read File    - 7.148699998855591 ms', 'type': 3}
:: [16:17:28.935] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: cache#load] Link Symbols - 0.49970000982284546 ms', 'type': 3}
:: [16:17:28.935] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: cache#load] Total        - 7.648400008678436 ms', 'type': 3}
:: [16:17:28.935] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: project#init] Done: Load Cache in 8.92059999704361 ms', 'type': 3}
LSP-Spyglass: [Profiler: project#init] Done: Load Config in 3.7140000015497208 ms
:: [16:17:29.019] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: project#init] Done: Load Config in 3.7140000015497208 ms', 'type': 3}
LSP-Spyglass: [Downloader] [mc-je/versions.json.gz.commit-sha] Downloaded from “https://api.github.com/repos/misode/mcmeta/git/refs/heads/summary”
:: [16:17:29.358] <-  LSP-Spyglass window/logMessage: {'message': '[Downloader] [mc-je/versions.json.gz.commit-sha] Downloaded from “https://api.github.com/repos/misode/mcmeta/git/refs/heads/summary”', 'type': 3}
LSP-Spyglass: [Downloader] [mc-je/versions.json.gz] Skipped downloading thanks to cache 15f05b54846b0cc5adebe63b245c7045ba105709
:: [16:17:29.360] <-  LSP-Spyglass window/logMessage: {'message': '[Downloader] [mc-je/versions.json.gz] Skipped downloading thanks to cache 15f05b54846b0cc5adebe63b245c7045ba105709', 'type': 3}
LSP-Spyglass: [je.initialize] Failed loading pack.mcmeta “file:///C:/Users/benaz/Downloads/fafik77%20RNG/pack.mcmeta” Error: Unknown pack_format “3”
    at Object.assert (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/dependency/common.js:34:19)
    at getPackMcmeta (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/index.js:18:24)
    at async initialize (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/index.js:35:24)
    at async Promise.allSettled (index 1)
    at async callIntializers (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/service/Project.js:237:29)
    at async init (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/service/Project.js:257:13)
LSP-Spyglass: [Downloader] [mc-je/1.20.1/blocks.json.gz.commit-sha] Skipped thanks to valid cache in memory
:: [16:17:29.367] <-  LSP-Spyglass window/logMessage: {'message': '[je.initialize] Failed loading pack.mcmeta “file:///C:/Users/benaz/Downloads/fafik77%20RNG/pack.mcmeta” Error: Unknown pack_format “3”\n    at Object.assert (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/dependency/common.js:34:19)\n    at getPackMcmeta (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/index.js:18:24)\n    at async initialize (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/index.js:35:24)\n    at async Promise.allSettled (index 1)\n    at async callIntializers (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/service/Project.js:237:29)\n    at async init (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/service/Project.js:257:13)', 'type': 1}
:: [16:17:29.368] <-  LSP-Spyglass window/logMessage: {'message': '[Downloader] [mc-je/1.20.1/blocks.json.gz.commit-sha] Skipped thanks to valid cache in memory', 'type': 3}
LSP-Spyglass: [Downloader] [mc-je/1.20.1/blocks.json.gz] Skipped downloading thanks to cache 15f05b54846b0cc5adebe63b245c7045ba105709
LSP-Spyglass: [Downloader] [mc-je/1.20.1/commands.json.gz.commit-sha] Skipped thanks to valid cache in memory
:: [16:17:29.376] <-  LSP-Spyglass window/logMessage: {'message': '[Downloader] [mc-je/1.20.1/blocks.json.gz] Skipped downloading thanks to cache 15f05b54846b0cc5adebe63b245c7045ba105709', 'type': 3}
:: [16:17:29.376] <-  LSP-Spyglass window/logMessage: {'message': '[Downloader] [mc-je/1.20.1/commands.json.gz.commit-sha] Skipped thanks to valid cache in memory', 'type': 3}
LSP-Spyglass: [Downloader] [mc-je/1.20.1/commands.json.gz] Skipped downloading thanks to cache 15f05b54846b0cc5adebe63b245c7045ba105709
LSP-Spyglass: [Downloader] [mc-je/1.20.1/registries.json.gz.commit-sha] Skipped thanks to valid cache in memory
:: [16:17:29.383] <-  LSP-Spyglass window/logMessage: {'message': '[Downloader] [mc-je/1.20.1/commands.json.gz] Skipped downloading thanks to cache 15f05b54846b0cc5adebe63b245c7045ba105709', 'type': 3}
:: [16:17:29.384] <-  LSP-Spyglass window/logMessage: {'message': '[Downloader] [mc-je/1.20.1/registries.json.gz.commit-sha] Skipped thanks to valid cache in memory', 'type': 3}
LSP-Spyglass: [Downloader] [mc-je/1.20.1/registries.json.gz] Skipped downloading thanks to cache 15f05b54846b0cc5adebe63b245c7045ba105709
LSP-Spyglass: [Project] [callInitializers] [1] “initialize” TypeError: Cannot read properties of null (reading 'slice')
    at Object.cmp (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/dependency/common.js:10:35)
    at getPatch (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/mcfunction/tree/patch.js:11:31)
    at Module.initialize (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/mcfunction/index.js:17:73)
    at initialize (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/index.js:59:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 1)
    at async callIntializers (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/service/Project.js:237:29)
    at async init (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/service/Project.js:257:13)
LSP-Spyglass: [Profiler: project#init] Done: Initialize in 458.21970000863075 ms
LSP-Spyglass: [Profiler: project#init] == Summary ==
LSP-Spyglass: [Profiler: project#init] Load Cache  - 8.92059999704361 ms
LSP-Spyglass: [Profiler: project#init] Load Config - 3.7140000015497208 ms
LSP-Spyglass: [Profiler: project#init] Initialize  - 458.21970000863075 ms
LSP-Spyglass: [Profiler: project#init] Total       - 470.8543000072241 ms
:: [16:17:29.408] <-  LSP-Spyglass window/logMessage: {'message': '[Downloader] [mc-je/1.20.1/registries.json.gz] Skipped downloading thanks to cache 15f05b54846b0cc5adebe63b245c7045ba105709', 'type': 3}
:: [16:17:29.408] <-  LSP-Spyglass window/logMessage: {'message': "[Project] [callInitializers] [1] “initialize” TypeError: Cannot read properties of null (reading 'slice')\n    at Object.cmp (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/dependency/common.js:10:35)\n    at getPatch (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/mcfunction/tree/patch.js:11:31)\n    at Module.initialize (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/mcfunction/index.js:17:73)\n    at initialize (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/java-edition/lib/index.js:59:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.allSettled (index 1)\n    at async callIntializers (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/service/Project.js:237:29)\n    at async init (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/service/Project.js:257:13)", 'type': 1}
:: [16:17:29.408] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: project#init] Done: Initialize in 458.21970000863075 ms', 'type': 3}
:: [16:17:29.408] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: project#init] == Summary ==', 'type': 3}
:: [16:17:29.409] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: project#init] Load Cache  - 8.92059999704361 ms', 'type': 3}
:: [16:17:29.409] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: project#init] Load Config - 3.7140000015497208 ms', 'type': 3}
:: [16:17:29.409] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: project#init] Initialize  - 458.21970000863075 ms', 'type': 3}
:: [16:17:29.409] <-  LSP-Spyglass window/logMessage: {'message': '[Profiler: project#init] Total       - 470.8543000072241 ms', 'type': 3}
:: [16:17:29.409] <<< LSP-Spyglass (1) (duration: 1849ms): {'capabilities': {'hoverProvider': {}, 'documentSymbolProvider': {'label': 'Spyglass'}, 'completionProvider': {'triggerCharacters': ['\n', ':', '"']}, 'semanticTokensProvider': {'documentSelector': [{'language': 'mcdoc'}, {'language': 'json'}], 'range': True, 'full': {'delta': False}, 'legend': {'tokenTypes': ['comment', 'enum', 'enumMember', 'function', 'keyword', 'modifier', 'number', 'operator', 'property', 'string', 'struct', 'type', 'type', 'variable', 'error', 'literal', 'operator', 'resourceLocation', 'vector'], 'tokenModifiers': ['declaration', 'defaultLibrary', 'definition', 'deprecated', 'documentation', 'modification', 'readonly']}}, 'experimental': {'spyglassmc': {'dataHackPubify': True, 'resetProjectCache': True, 'inlayHints': True, 'showCacheRoot': True}}, 'referencesProvider': {}, 'documentHighlightProvider': {}, 'workspaceSymbolProvider': {}, 'declarationProvider': {}, 'signatureHelpProvider': {'triggerCharacters': [' ']}, 'definitionProvider': {}, 'textDocumentSync': {'didOpen': {}, 'didClose': {}, 'change': {'syncKind': 2}}, 'colorProvider': {}, 'workspace': {'workspaceFolders': {'supported': True, 'changeNotifications': True}}, 'implementationProvider': {}, 'typeDefinitionProvider': {}, 'documentFormattingProvider': {}}, 'serverInfo': {'name': 'Spyglass Language Server'}}
:: [16:17:29.410]  -> LSP-Spyglass initialized: {}
LSP-Spyglass: file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/service/MetaRegistry.js:172
LSP-Spyglass:         throw new Error(`There is no parser registered for language ID '${languageID}'`);
LSP-Spyglass:               ^
LSP-Spyglass: 
LSP-Spyglass: Error: There is no parser registered for language ID 'mcfunction'
LSP-Spyglass:     at MetaRegistry.getParserForLanguageId (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/service/MetaRegistry.js:172:15)
LSP-Spyglass:     at file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/parser/file.js:20:33
LSP-Spyglass:     at Project.parse (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/service/Project.js:491:28)
LSP-Spyglass:     at Project.onDidOpen (file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/core/lib/service/Project.js:605:27)
LSP-Spyglass:     at file:///C:/Users/benaz/AppData/Local/Sublime%20Text/Package%20Storage/LSP-Spyglass/18.16.0/language-server/node_modules/@spyglassmc/language-server/lib/server.js:159:28
LSP-Spyglass:     at handleNotification (C:\Users\benaz\AppData\Local\Sublime Text\Package Storage\LSP-Spyglass\18.16.0\language-server\node_modules\vscode-jsonrpc\lib\common\connection.js:547:25)
LSP-Spyglass:     at processMessageQueue (C:\Users\benaz\AppData\Local\Sublime Text\Package Storage\LSP-Spyglass\18.16.0\language-server\node_modules\vscode-jsonrpc\lib\common\connection.js:289:17)
LSP-Spyglass:     at Immediate.<anonymous> (C:\Users\benaz\AppData\Local\Sublime Text\Package Storage\LSP-Spyglass\18.16.0\language-server\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
LSP-Spyglass:     at process.processImmediate (node:internal/timers:476:21)
LSP-Spyglass: 
LSP-Spyglass: Node.js v18.16.0
:: [16:17:29.555]  -> LSP-Spyglass textDocument/didOpen: {'textDocument': {'text': '### fafik77 uninstall\n\n #\tadded scores\nscoreboard objectives remove RNG_77\nscoreboard objectives remove RNG_77_rp\n', 'version': 0, 'uri': 'file:///C:/Users/benaz/Downloads/fafik77%20RNG/data/fafik77/functions/rng/uninstall.mcfunction', 'languageId': 'mcfunction'}}
:: [16:17:29.555] --> LSP-Spyglass textDocument/documentColor (2): {'textDocument': {'uri': 'file:///C:/Users/benaz/Downloads/fafik77%20RNG/data/fafik77/functions/rng/uninstall.mcfunction'}}
```

**Comment by SPGoding** [comment]
Duplicate of SpyglassMC/LSP-Spyglass#1

**Comment by SPGoding** [comment]
Nvm I thought this was a Sublime Text-specific problem. It's actually caused by some newer versions of Minecraft having `null` as their `release_target`s.

**Comment by misode** [comment]
Fixed in fd953bb14eaf862d925b4d276fb6fa77675fe7a1
