### ISSUE TITLE
configured_sctructure_feature is required when it shouldn't be

### ISSUE THREAD

**Issue by gBonvenuto** [SpyglassMC/Spyglass#1067]
https://github.com/SpyglassMC/Spyglass/assets/25495557/9612e7f7-3e48-4e09-ae24-e61d5f2bc6ea

OS: Pop!_OS 22.04 LTS x86_64
Kernel: 6.2.6-76060206-generic

Logs:

```
[onInitialize] CacheVersion = 11
[onInitialize] ReleaseNotesVersion = 3.1.0
[onInitialize] globalStoragePath = /home/giancarlo-pop-os/.config/Code/User/globalStorage/spgoding.datapack-language-server
[onInitialize] cachePath = /home/giancarlo-pop-os/.config/Code/User/workspaceStorage/4c3ba1f9076bd134bdd06853aefebe44/SPGoding.datapack-language-server/cache.json
[onInitialize] pluginsPath = /home/giancarlo-pop-os/.config/Code/User/globalStorage/spgoding.datapack-language-server/plugins
[PluginLoader] Registered “spgoding:doc_comment”
[PluginLoader] Registered “spgoding:mcfunction”
[PluginLoader] 0 ms
[LatestVersions] Fetching the latest versions...
[LatestVersions] versionInformation = {"latestRelease":"1.20.1","latestSnapshot":"1.20.1","processedVersions":["1.20.1","1.20.1-rc1","1.20","1.20-rc1","1.20-pre7","1.20-pre6","1.20-pre5","1.20-pre4","1.20-pre3","1.20-pre2","1.20-pre1","23w18a","23w17a","23w16a","23w14a","23w13a_or_b","23w13a","23w12a","1.19.4","1.19.4-rc3","1.19.4-rc2","1.19.4-rc1","1.19.4-pre4","1.19.4-pre3","1.19.4-pre2","1.19.4-pre1","23w07a","23w06a","23w05a","23w04a","23w03a","1.19.3","1.19.3-rc3","1.19.3-rc2","1.19.3-rc1","1.19.3-pre3","1.19.3-pre2","1.19.3-pre1","22w46a","22w45a","22w44a","22w43a","22w42a","1.19.2","1.19.2-rc2","1.19.2-rc1","1.19.1","1.19.1-rc3","1.19.1-rc2","1.19.1-pre6","1.19.1-pre5","1.19.1-pre4","1.19.1-pre3","1.19.1-pre2","1.19.1-rc1","1.19.1-pre1","22w24a","1.19","1.19-rc2","1.19-rc1","1.19-pre5","1.19-pre4","1.19-pre3","1.19-pre2","1.19-pre1","22w19a","22w18a","22w17a","22w16b","22w16a","22w15a","22w14a","22w13oneblockatatime","22w13a","22w12a","22w11a","1.18.2","1.18.2-rc1","1.18.2-pre3","1.18.2-pre2","1.18.2-pre1","22w07a","22w06a","22w05a","22w03a","1.18.1","1.18.1-rc3","1.18.1-rc2","1.18.1-rc1","1.18.1-pre1","1.18","1.18-rc4","1.18-rc3","1.18-rc2","1.18-rc1","1.18-pre8","1.18-pre7","1.18-pre6","1.18-pre5","1.18-pre4","1.18-pre3","1.18-pre2","1.18-pre1","21w44a","21w43a","21w42a","21w41a","21w40a","21w39a","21w38a","21w37a","1.17.1","1.17.1-rc2","1.17.1-rc1","1.17.1-pre3","1.17.1-pre2","1.17.1-pre1","1.17","1.17-rc2","1.17-rc1","1.17-pre5","1.17-pre4","1.17-pre3","1.17-pre2","1.17-pre1","21w20a","21w19a","21w18a","21w17a","21w16a","21w15a","21w14a","21w13a","21w11a","21w10a","21w08b","21w08a","21w07a","21w06a","21w05b","21w05a","21w03a","1.16.5","1.16.5-rc1","20w51a","20w49a","20w48a","20w46a","20w45a","1.16.4","1.16.4-rc1","1.16.4-pre2","1.16.4-pre1","1.16.3","1.16.3-rc1","1.16.2"]}
[I18N] Set to “en”.
[VanillaData: BlockDefinition for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/BlockDefinition.json...
[updateRoots] Data pack 1 = “file:///home/giancarlo-pop-os/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.19/.minecraft/saves/Novo%20mundo/datapacks/jungle-update/”
[VanillaData: BlockDefinition for 1.20.1] Loaded from local file.
[VanillaData: NamespaceSummary for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/NamespaceSummary.json...
[VanillaData: NamespaceSummary for 1.20.1] Loaded from local file.
[VanillaData: Nbtdoc for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/Nbtdoc.json...
[VanillaData: Nbtdoc for 1.20.1] Loaded from local file.
[VanillaData: Registry for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/Registry.json...
[VanillaData: Registry for 1.20.1] Loaded from local file.
Tried to access schema "configured_structure_feature", but that doesn't exist.
[Error - 12:11:17] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Cannot read properties of undefined (reading 'default')
  Code: -32603 
[uncaughtException] the language server will be terminated:  TypeError: Cannot read properties of undefined (reading 'default')
    at new n (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:289921)
    at _.setUp (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:317687)
    at _.validate (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:316037)
    at t.parseJsonNode (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:163490)
    at N.parseJsonDocument (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:523648)
    at N.<anonymous> (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:523242)
    at Generator.next (<anonymous>)
    at n (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:517220)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[Info  - 12:11:17] Connection to server got closed. Server will restart.
[onInitialize] CacheVersion = 11
[onInitialize] ReleaseNotesVersion = 3.1.0
[onInitialize] globalStoragePath = /home/giancarlo-pop-os/.config/Code/User/globalStorage/spgoding.datapack-language-server
[onInitialize] cachePath = /home/giancarlo-pop-os/.config/Code/User/workspaceStorage/4c3ba1f9076bd134bdd06853aefebe44/SPGoding.datapack-language-server/cache.json
[onInitialize] pluginsPath = /home/giancarlo-pop-os/.config/Code/User/globalStorage/spgoding.datapack-language-server/plugins
[PluginLoader] Registered “spgoding:doc_comment”
[PluginLoader] Registered “spgoding:mcfunction”
[PluginLoader] 0 ms
[LatestVersions] Fetching the latest versions...
[LatestVersions] versionInformation = {"latestRelease":"1.20.1","latestSnapshot":"1.20.1","processedVersions":["1.20.1","1.20.1-rc1","1.20","1.20-rc1","1.20-pre7","1.20-pre6","1.20-pre5","1.20-pre4","1.20-pre3","1.20-pre2","1.20-pre1","23w18a","23w17a","23w16a","23w14a","23w13a_or_b","23w13a","23w12a","1.19.4","1.19.4-rc3","1.19.4-rc2","1.19.4-rc1","1.19.4-pre4","1.19.4-pre3","1.19.4-pre2","1.19.4-pre1","23w07a","23w06a","23w05a","23w04a","23w03a","1.19.3","1.19.3-rc3","1.19.3-rc2","1.19.3-rc1","1.19.3-pre3","1.19.3-pre2","1.19.3-pre1","22w46a","22w45a","22w44a","22w43a","22w42a","1.19.2","1.19.2-rc2","1.19.2-rc1","1.19.1","1.19.1-rc3","1.19.1-rc2","1.19.1-pre6","1.19.1-pre5","1.19.1-pre4","1.19.1-pre3","1.19.1-pre2","1.19.1-rc1","1.19.1-pre1","22w24a","1.19","1.19-rc2","1.19-rc1","1.19-pre5","1.19-pre4","1.19-pre3","1.19-pre2","1.19-pre1","22w19a","22w18a","22w17a","22w16b","22w16a","22w15a","22w14a","22w13oneblockatatime","22w13a","22w12a","22w11a","1.18.2","1.18.2-rc1","1.18.2-pre3","1.18.2-pre2","1.18.2-pre1","22w07a","22w06a","22w05a","22w03a","1.18.1","1.18.1-rc3","1.18.1-rc2","1.18.1-rc1","1.18.1-pre1","1.18","1.18-rc4","1.18-rc3","1.18-rc2","1.18-rc1","1.18-pre8","1.18-pre7","1.18-pre6","1.18-pre5","1.18-pre4","1.18-pre3","1.18-pre2","1.18-pre1","21w44a","21w43a","21w42a","21w41a","21w40a","21w39a","21w38a","21w37a","1.17.1","1.17.1-rc2","1.17.1-rc1","1.17.1-pre3","1.17.1-pre2","1.17.1-pre1","1.17","1.17-rc2","1.17-rc1","1.17-pre5","1.17-pre4","1.17-pre3","1.17-pre2","1.17-pre1","21w20a","21w19a","21w18a","21w17a","21w16a","21w15a","21w14a","21w13a","21w11a","21w10a","21w08b","21w08a","21w07a","21w06a","21w05b","21w05a","21w03a","1.16.5","1.16.5-rc1","20w51a","20w49a","20w48a","20w46a","20w45a","1.16.4","1.16.4-rc1","1.16.4-pre2","1.16.4-pre1","1.16.3","1.16.3-rc1","1.16.2"]}
[I18N] Set to “en”.
[VanillaData: BlockDefinition for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/BlockDefinition.json...
[updateRoots] Data pack 1 = “file:///home/giancarlo-pop-os/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.19/.minecraft/saves/Novo%20mundo/datapacks/jungle-update/”
[VanillaData: BlockDefinition for 1.20.1] Loaded from local file.
[VanillaData: NamespaceSummary for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/NamespaceSummary.json...
[VanillaData: NamespaceSummary for 1.20.1] Loaded from local file.
[VanillaData: Nbtdoc for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/Nbtdoc.json...
[VanillaData: Nbtdoc for 1.20.1] Loaded from local file.
[VanillaData: Registry for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/Registry.json...
[VanillaData: Registry for 1.20.1] Loaded from local file.
Tried to access schema "configured_structure_feature", but that doesn't exist.
[Error - 12:11:18] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Cannot read properties of undefined (reading 'default')
  Code: -32603 
[uncaughtException] the language server will be terminated:  TypeError: Cannot read properties of undefined (reading 'default')
    at new n (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:289921)
    at _.setUp (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:317687)
    at _.validate (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:316037)
    at t.parseJsonNode (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:163490)
    at N.parseJsonDocument (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:523648)
    at N.<anonymous> (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:523242)
    at Generator.next (<anonymous>)
    at n (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:517220)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[Info  - 12:11:18] Connection to server got closed. Server will restart.
[onInitialize] CacheVersion = 11
[onInitialize] ReleaseNotesVersion = 3.1.0
[onInitialize] globalStoragePath = /home/giancarlo-pop-os/.config/Code/User/globalStorage/spgoding.datapack-language-server
[onInitialize] cachePath = /home/giancarlo-pop-os/.config/Code/User/workspaceStorage/4c3ba1f9076bd134bdd06853aefebe44/SPGoding.datapack-language-server/cache.json
[onInitialize] pluginsPath = /home/giancarlo-pop-os/.config/Code/User/globalStorage/spgoding.datapack-language-server/plugins
[PluginLoader] Registered “spgoding:doc_comment”
[PluginLoader] Registered “spgoding:mcfunction”
[PluginLoader] 0 ms
[LatestVersions] Fetching the latest versions...
[LatestVersions] versionInformation = {"latestRelease":"1.20.1","latestSnapshot":"1.20.1","processedVersions":["1.20.1","1.20.1-rc1","1.20","1.20-rc1","1.20-pre7","1.20-pre6","1.20-pre5","1.20-pre4","1.20-pre3","1.20-pre2","1.20-pre1","23w18a","23w17a","23w16a","23w14a","23w13a_or_b","23w13a","23w12a","1.19.4","1.19.4-rc3","1.19.4-rc2","1.19.4-rc1","1.19.4-pre4","1.19.4-pre3","1.19.4-pre2","1.19.4-pre1","23w07a","23w06a","23w05a","23w04a","23w03a","1.19.3","1.19.3-rc3","1.19.3-rc2","1.19.3-rc1","1.19.3-pre3","1.19.3-pre2","1.19.3-pre1","22w46a","22w45a","22w44a","22w43a","22w42a","1.19.2","1.19.2-rc2","1.19.2-rc1","1.19.1","1.19.1-rc3","1.19.1-rc2","1.19.1-pre6","1.19.1-pre5","1.19.1-pre4","1.19.1-pre3","1.19.1-pre2","1.19.1-rc1","1.19.1-pre1","22w24a","1.19","1.19-rc2","1.19-rc1","1.19-pre5","1.19-pre4","1.19-pre3","1.19-pre2","1.19-pre1","22w19a","22w18a","22w17a","22w16b","22w16a","22w15a","22w14a","22w13oneblockatatime","22w13a","22w12a","22w11a","1.18.2","1.18.2-rc1","1.18.2-pre3","1.18.2-pre2","1.18.2-pre1","22w07a","22w06a","22w05a","22w03a","1.18.1","1.18.1-rc3","1.18.1-rc2","1.18.1-rc1","1.18.1-pre1","1.18","1.18-rc4","1.18-rc3","1.18-rc2","1.18-rc1","1.18-pre8","1.18-pre7","1.18-pre6","1.18-pre5","1.18-pre4","1.18-pre3","1.18-pre2","1.18-pre1","21w44a","21w43a","21w42a","21w41a","21w40a","21w39a","21w38a","21w37a","1.17.1","1.17.1-rc2","1.17.1-rc1","1.17.1-pre3","1.17.1-pre2","1.17.1-pre1","1.17","1.17-rc2","1.17-rc1","1.17-pre5","1.17-pre4","1.17-pre3","1.17-pre2","1.17-pre1","21w20a","21w19a","21w18a","21w17a","21w16a","21w15a","21w14a","21w13a","21w11a","21w10a","21w08b","21w08a","21w07a","21w06a","21w05b","21w05a","21w03a","1.16.5","1.16.5-rc1","20w51a","20w49a","20w48a","20w46a","20w45a","1.16.4","1.16.4-rc1","1.16.4-pre2","1.16.4-pre1","1.16.3","1.16.3-rc1","1.16.2"]}
[I18N] Set to “en”.
[VanillaData: BlockDefinition for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/BlockDefinition.json...
[updateRoots] Data pack 1 = “file:///home/giancarlo-pop-os/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.19/.minecraft/saves/Novo%20mundo/datapacks/jungle-update/”
[VanillaData: BlockDefinition for 1.20.1] Loaded from local file.
[VanillaData: NamespaceSummary for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/NamespaceSummary.json...
[VanillaData: NamespaceSummary for 1.20.1] Loaded from local file.
[VanillaData: Nbtdoc for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/Nbtdoc.json...
[VanillaData: Nbtdoc for 1.20.1] Loaded from local file.
[VanillaData: Registry for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/Registry.json...
[VanillaData: Registry for 1.20.1] Loaded from local file.
Tried to access schema "configured_structure_feature", but that doesn't exist.
[Error - 12:11:19] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Cannot read properties of undefined (reading 'default')
  Code: -32603 
[uncaughtException] the language server will be terminated:  TypeError: Cannot read properties of undefined (reading 'default')
    at new n (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:289921)
    at _.setUp (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:317687)
    at _.validate (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:316037)
    at t.parseJsonNode (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:163490)
    at N.parseJsonDocument (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:523648)
    at N.<anonymous> (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:523242)
    at Generator.next (<anonymous>)
    at n (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:517220)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[Info  - 12:11:19] Connection to server got closed. Server will restart.
[onInitialize] CacheVersion = 11
[onInitialize] ReleaseNotesVersion = 3.1.0
[onInitialize] globalStoragePath = /home/giancarlo-pop-os/.config/Code/User/globalStorage/spgoding.datapack-language-server
[onInitialize] cachePath = /home/giancarlo-pop-os/.config/Code/User/workspaceStorage/4c3ba1f9076bd134bdd06853aefebe44/SPGoding.datapack-language-server/cache.json
[onInitialize] pluginsPath = /home/giancarlo-pop-os/.config/Code/User/globalStorage/spgoding.datapack-language-server/plugins
[PluginLoader] Registered “spgoding:doc_comment”
[PluginLoader] Registered “spgoding:mcfunction”
[PluginLoader] 0 ms
[LatestVersions] Fetching the latest versions...
[LatestVersions] versionInformation = {"latestRelease":"1.20.1","latestSnapshot":"1.20.1","processedVersions":["1.20.1","1.20.1-rc1","1.20","1.20-rc1","1.20-pre7","1.20-pre6","1.20-pre5","1.20-pre4","1.20-pre3","1.20-pre2","1.20-pre1","23w18a","23w17a","23w16a","23w14a","23w13a_or_b","23w13a","23w12a","1.19.4","1.19.4-rc3","1.19.4-rc2","1.19.4-rc1","1.19.4-pre4","1.19.4-pre3","1.19.4-pre2","1.19.4-pre1","23w07a","23w06a","23w05a","23w04a","23w03a","1.19.3","1.19.3-rc3","1.19.3-rc2","1.19.3-rc1","1.19.3-pre3","1.19.3-pre2","1.19.3-pre1","22w46a","22w45a","22w44a","22w43a","22w42a","1.19.2","1.19.2-rc2","1.19.2-rc1","1.19.1","1.19.1-rc3","1.19.1-rc2","1.19.1-pre6","1.19.1-pre5","1.19.1-pre4","1.19.1-pre3","1.19.1-pre2","1.19.1-rc1","1.19.1-pre1","22w24a","1.19","1.19-rc2","1.19-rc1","1.19-pre5","1.19-pre4","1.19-pre3","1.19-pre2","1.19-pre1","22w19a","22w18a","22w17a","22w16b","22w16a","22w15a","22w14a","22w13oneblockatatime","22w13a","22w12a","22w11a","1.18.2","1.18.2-rc1","1.18.2-pre3","1.18.2-pre2","1.18.2-pre1","22w07a","22w06a","22w05a","22w03a","1.18.1","1.18.1-rc3","1.18.1-rc2","1.18.1-rc1","1.18.1-pre1","1.18","1.18-rc4","1.18-rc3","1.18-rc2","1.18-rc1","1.18-pre8","1.18-pre7","1.18-pre6","1.18-pre5","1.18-pre4","1.18-pre3","1.18-pre2","1.18-pre1","21w44a","21w43a","21w42a","21w41a","21w40a","21w39a","21w38a","21w37a","1.17.1","1.17.1-rc2","1.17.1-rc1","1.17.1-pre3","1.17.1-pre2","1.17.1-pre1","1.17","1.17-rc2","1.17-rc1","1.17-pre5","1.17-pre4","1.17-pre3","1.17-pre2","1.17-pre1","21w20a","21w19a","21w18a","21w17a","21w16a","21w15a","21w14a","21w13a","21w11a","21w10a","21w08b","21w08a","21w07a","21w06a","21w05b","21w05a","21w03a","1.16.5","1.16.5-rc1","20w51a","20w49a","20w48a","20w46a","20w45a","1.16.4","1.16.4-rc1","1.16.4-pre2","1.16.4-pre1","1.16.3","1.16.3-rc1","1.16.2"]}
[I18N] Set to “en”.
[VanillaData: BlockDefinition for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/BlockDefinition.json...
[updateRoots] Data pack 1 = “file:///home/giancarlo-pop-os/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.19/.minecraft/saves/Novo%20mundo/datapacks/jungle-update/”
[VanillaData: BlockDefinition for 1.20.1] Loaded from local file.
[VanillaData: NamespaceSummary for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/NamespaceSummary.json...
[VanillaData: NamespaceSummary for 1.20.1] Loaded from local file.
[VanillaData: Nbtdoc for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/Nbtdoc.json...
[VanillaData: Nbtdoc for 1.20.1] Loaded from local file.
[VanillaData: Registry for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/Registry.json...
[VanillaData: Registry for 1.20.1] Loaded from local file.
Tried to access schema "configured_structure_feature", but that doesn't exist.
[Error - 12:11:19] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Cannot read properties of undefined (reading 'default')
  Code: -32603 
[uncaughtException] the language server will be terminated:  TypeError: Cannot read properties of undefined (reading 'default')
    at new n (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:289921)
    at _.setUp (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:317687)
    at _.validate (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:316037)
    at t.parseJsonNode (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:163490)
    at N.parseJsonDocument (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:523648)
    at N.<anonymous> (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:523242)
    at Generator.next (<anonymous>)
    at n (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:517220)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[Info  - 12:11:19] Connection to server got closed. Server will restart.
[onInitialize] CacheVersion = 11
[onInitialize] ReleaseNotesVersion = 3.1.0
[onInitialize] globalStoragePath = /home/giancarlo-pop-os/.config/Code/User/globalStorage/spgoding.datapack-language-server
[onInitialize] cachePath = /home/giancarlo-pop-os/.config/Code/User/workspaceStorage/4c3ba1f9076bd134bdd06853aefebe44/SPGoding.datapack-language-server/cache.json
[onInitialize] pluginsPath = /home/giancarlo-pop-os/.config/Code/User/globalStorage/spgoding.datapack-language-server/plugins
[PluginLoader] Registered “spgoding:doc_comment”
[PluginLoader] Registered “spgoding:mcfunction”
[PluginLoader] 0 ms
[LatestVersions] Fetching the latest versions...
[LatestVersions] versionInformation = {"latestRelease":"1.20.1","latestSnapshot":"1.20.1","processedVersions":["1.20.1","1.20.1-rc1","1.20","1.20-rc1","1.20-pre7","1.20-pre6","1.20-pre5","1.20-pre4","1.20-pre3","1.20-pre2","1.20-pre1","23w18a","23w17a","23w16a","23w14a","23w13a_or_b","23w13a","23w12a","1.19.4","1.19.4-rc3","1.19.4-rc2","1.19.4-rc1","1.19.4-pre4","1.19.4-pre3","1.19.4-pre2","1.19.4-pre1","23w07a","23w06a","23w05a","23w04a","23w03a","1.19.3","1.19.3-rc3","1.19.3-rc2","1.19.3-rc1","1.19.3-pre3","1.19.3-pre2","1.19.3-pre1","22w46a","22w45a","22w44a","22w43a","22w42a","1.19.2","1.19.2-rc2","1.19.2-rc1","1.19.1","1.19.1-rc3","1.19.1-rc2","1.19.1-pre6","1.19.1-pre5","1.19.1-pre4","1.19.1-pre3","1.19.1-pre2","1.19.1-rc1","1.19.1-pre1","22w24a","1.19","1.19-rc2","1.19-rc1","1.19-pre5","1.19-pre4","1.19-pre3","1.19-pre2","1.19-pre1","22w19a","22w18a","22w17a","22w16b","22w16a","22w15a","22w14a","22w13oneblockatatime","22w13a","22w12a","22w11a","1.18.2","1.18.2-rc1","1.18.2-pre3","1.18.2-pre2","1.18.2-pre1","22w07a","22w06a","22w05a","22w03a","1.18.1","1.18.1-rc3","1.18.1-rc2","1.18.1-rc1","1.18.1-pre1","1.18","1.18-rc4","1.18-rc3","1.18-rc2","1.18-rc1","1.18-pre8","1.18-pre7","1.18-pre6","1.18-pre5","1.18-pre4","1.18-pre3","1.18-pre2","1.18-pre1","21w44a","21w43a","21w42a","21w41a","21w40a","21w39a","21w38a","21w37a","1.17.1","1.17.1-rc2","1.17.1-rc1","1.17.1-pre3","1.17.1-pre2","1.17.1-pre1","1.17","1.17-rc2","1.17-rc1","1.17-pre5","1.17-pre4","1.17-pre3","1.17-pre2","1.17-pre1","21w20a","21w19a","21w18a","21w17a","21w16a","21w15a","21w14a","21w13a","21w11a","21w10a","21w08b","21w08a","21w07a","21w06a","21w05b","21w05a","21w03a","1.16.5","1.16.5-rc1","20w51a","20w49a","20w48a","20w46a","20w45a","1.16.4","1.16.4-rc1","1.16.4-pre2","1.16.4-pre1","1.16.3","1.16.3-rc1","1.16.2"]}
[I18N] Set to “en”.
[VanillaData: BlockDefinition for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/BlockDefinition.json...
[updateRoots] Data pack 1 = “file:///home/giancarlo-pop-os/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/1.19/.minecraft/saves/Novo%20mundo/datapacks/jungle-update/”
[VanillaData: BlockDefinition for 1.20.1] Loaded from local file.
[VanillaData: NamespaceSummary for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/NamespaceSummary.json...
[VanillaData: NamespaceSummary for 1.20.1] Loaded from local file.
[VanillaData: Nbtdoc for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/Nbtdoc.json...
[VanillaData: Nbtdoc for 1.20.1] Loaded from local file.
[VanillaData: Registry for 1.20.1] Loading from local file ${globalStoragePath}/1.20.1/Registry.json...
[VanillaData: Registry for 1.20.1] Loaded from local file.
Tried to access schema "configured_structure_feature", but that doesn't exist.
[Error - 12:11:20] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Cannot read properties of undefined (reading 'default')
  Code: -32603 
[uncaughtException] the language server will be terminated:  TypeError: Cannot read properties of undefined (reading 'default')
    at new n (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:289921)
    at _.setUp (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:317687)
    at _.validate (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:316037)
    at t.parseJsonNode (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:163490)
    at N.parseJsonDocument (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:523648)
    at N.<anonymous> (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:523242)
    at Generator.next (<anonymous>)
    at n (/home/giancarlo-pop-os/.vscode/extensions/spgoding.datapack-language-server-3.4.16/dist/server.js:1:517220)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[Error - 12:11:20] Connection to server got closed. Server will not be restarted.
```

**Comment by gBonvenuto** [comment]
I was following an old tutorial, it seems minecraft datapacks changed. Now that I followed the [wiki](https://minecraft.fandom.com/wiki/Custom_structure), it works. But still, the VSCode extension requires a `configured_structure_feature` folder when it shouldn't exist anymore.

![image](https://github.com/SpyglassMC/Spyglass/assets/25495557/57321e28-470b-4c78-9433-f901c33ea711)

It should require a `sctructure` folder instead

**Comment by MulverineX** [comment]
Will be fixed in v4.

**Comment by SirReddev** [comment]
glad I see this here so I know I'm not doing something wrong
