### ISSUE TITLE
The Spyglass Language Server crashed

### ISSUE THREAD

**Issue by klue007** [SpyglassMC/Spyglass#1466]
I'm using v4.0.1 and after updated it says "The Spyglass Language Server server crashed 5 times in the last 3 minutes."

```
Error: There is no parser registered for language ID 'mcfunction'
    at H0.getParserForLanguageId (c:\Users\Lenovo\.vscode\extensions\spgoding.datapack-language-server-4.0.1\dist\server.js:69:7054)
    at To.parse (c:\Users\Lenovo\.vscode\extensions\spgoding.datapack-language-server-4.0.1\dist\server.js:69:18552)
    at To.onDidOpen (c:\Users\Lenovo\.vscode\extensions\spgoding.datapack-language-server-4.0.1\dist\server.js:69:20693)
    at c:\Users\Lenovo\.vscode\extensions\spgoding.datapack-language-server-4.0.1\dist\server.js:127:25509
    at Qe (c:\Users\Lenovo\.vscode\extensions\spgoding.datapack-language-server-4.0.1\dist\server.js:15:1561)
    at or (c:\Users\Lenovo\.vscode\extensions\spgoding.datapack-language-server-4.0.1\dist\server.js:14:6204)
    at be (c:\Users\Lenovo\.vscode\extensions\spgoding.datapack-language-server-4.0.1\dist\server.js:14:6357)
    at Immediate.<anonymous> (c:\Users\Lenovo\.vscode\extensions\spgoding.datapack-language-server-4.0.1\dist\server.js:14:6122)
    at process.processImmediate (node:internal/timers:478:21)

Node.js v20.9.0
[Error - 22:19:19] Server process exited with code 1.
[Error - 22:19:19] The Spyglass Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by misode** [comment]
Could you show a bit of the log above that error?

**Comment by klue007** [comment]
[log.txt](https://github.com/user-attachments/files/16086719/log.txt)

**Comment by misode** [comment]
It failed to download necessary resources for the language server to function. Is `api.github.com` or `raw.githubusercontent.com` blocked in your country? Maybe your DNS is configured incorrectly?

Try using another data source by creating a `spyglass.json` file at the root of your workspace:
```json
{
  "env": {
    "env": "jsDelivr"
  }
}
```

**Comment by SPGoding** [comment]
jsDelivr might not help with the `api.github.com` calls where we're trying to find out the latest commit hash.

**Comment by klue007** [comment]
> It failed to download necessary resources for the language server to function. Is `api.github.com` or `raw.githubusercontent.com` blocked in your country? Maybe your DNS is configured incorrectly?
> 
> Try using another data source by creating a `spyglass.json` file at the root of your workspace:
> 
> ```json
> {
>   "env": {
>     "env": "jsDelivr"
>   }
> }
> ```

It's some connection problem and I've found a way to fix it. Thanks for help!

**Comment by Lessering** [comment]
how did you solve that?
i still have that bug in all versions of 4.x
