### ISSUE TITLE
There is a probability of reporting errors for all strings.

### ISSUE THREAD

**Issue by WhiteElephant-abc** [SpyglassMC/Spyglass#1681]
DHP：v4.4.0
VScode：1.96.2

**Comment by misode** [comment]
Could you share a screenshot of the errors you are experiencing, or explain how to reproduce your issues?

**Comment by WhiteElephant-abc** [comment]
![Image](https://github.com/user-attachments/assets/ca4425ce-af5c-4b9e-9b65-b63a4da342f7)
![Image](https://github.com/user-attachments/assets/35b9c00d-bfc6-44d7-b497-3b75a82c9dab)
![Image](https://github.com/user-attachments/assets/13c03861-315e-4e71-8363-ae3a75898206)
![Image](https://github.com/user-attachments/assets/fd02ef87-2282-4418-b714-e795a22cf66e)
![Image](https://github.com/user-attachments/assets/b17a06a8-73f7-4b04-b37d-97329d8bf3aa)
This is a new computer. The old computer used to have this problem too, but it somehow got fixed later.

**Comment by WhiteElephant-abc** [comment]
[Info  - 13:32:46] [onInitialize] processId = 6544
[Info  - 13:32:46] [onInitialize] clientInfo = {"name":"Visual Studio Code","version":"1.96.2"}
[Info  - 13:32:46] [onInitialize] initializationOptions = {"inDevelopmentMode":false,"gameVersion":"Auto"}
[Error - 13:32:46] [loadLocale] Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\locales\zh.js' imported from c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:940:10)
    at defaultResolve (node:internal/modules/esm/resolve:1176:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:472:34)
    at defaultImportModuleDynamicallyForScript (node:internal/modules/esm/utils:227:31)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:249:12)
    at VT (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:51:17167) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///c:/Users/xiang/.vscode/extensions/spgoding.datapack-language-server-4.4.0/dist/locales/zh.js'
}
[Info  - 13:32:46] [Project] [init] cacheRoot = file:///C:/Users/xiang/AppData/Local/spyglassmc-nodejs/Cache/
[Info  - 13:32:46] [Project] [init] projectRoots = file:///d%3A/GitHub%20Desktop/datapackets-functions-LIB/ file:///d%3A/GitHub%20Desktop/iron-block-elevator/ file:///d%3A/GitHub%20Desktop/SetBlock-TNT/
[Info  - 13:32:46] [CacheService#load] symbolCachePath = file:///C:/Users/xiang/AppData/Local/spyglassmc-nodejs/Cache/symbols/ebf9e0c51a4cecd9d1246c11437231e75621bad4.json.gz
[Info  - 13:32:46] [Profiler: cache#load] Done: Read File in 75.7322 ms
[Info  - 13:32:46] [Profiler: cache#load] Done: Link Symbols in 37.66399999999999 ms
[Info  - 13:32:46] [Profiler: cache#load] == Summary ==
[Info  - 13:32:46] [Profiler: cache#load] Read File    - 75.7322 ms
[Info  - 13:32:46] [Profiler: cache#load] Link Symbols - 37.66399999999999 ms
[Info  - 13:32:46] [Profiler: cache#load] Total        - 113.3962 ms
[Info  - 13:32:46] [Profiler: project#init] Done: Load Cache in 184.98870000000002 ms
[Info  - 13:32:46] [Profiler: project#init] Done: Load Config in 4.706699999999955 ms
[Error - 13:32:46] [Downloader] [mc-je/versions.json.gz.commit-sha] Downloading https://api.github.com/repos/misode/mcmeta/git/refs/heads/summary Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1076:8)
    at ssl.onhandshakedone (node:_tls_wrap:862:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
[Info  - 13:32:47] [Downloader] [mc-je/versions.json.gz] Downloaded from https://raw.githubusercontent.com/misode/mcmeta/summary/versions/data.json.gz
[Info  - 13:32:47] [je.initialize] Found a valid pack.mcmeta file:///d%3A/GitHub%20Desktop/datapackets-functions-LIB/pack.mcmeta, using data pack format 48 to select version 1.21.1
[Error - 13:32:47] [Downloader] [mc-je/1.21.1/blocks.json.gz.commit-sha] Downloading https://api.github.com/repos/misode/mcmeta/git/refs/tags/1.21.1-summary Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1076:8)
    at ssl.onhandshakedone (node:_tls_wrap:862:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
[Info  - 13:32:48] [Downloader] [mc-je/1.21.1/blocks.json.gz] Downloaded from https://raw.githubusercontent.com/misode/mcmeta/1.21.1-summary/blocks/data.json.gz
[Error - 13:32:48] [Downloader] [mc-je/1.21.1/commands.json.gz.commit-sha] Downloading https://api.github.com/repos/misode/mcmeta/git/refs/tags/1.21.1-summary Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1076:8)
    at ssl.onhandshakedone (node:_tls_wrap:862:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
[Info  - 13:32:48] [Downloader] [mc-je/1.21.1/commands.json.gz] Downloaded from https://raw.githubusercontent.com/misode/mcmeta/1.21.1-summary/commands/data.json.gz
[Error - 13:32:48] [Downloader] [mc-je/1.21.1/registries.json.gz.commit-sha] Downloading https://api.github.com/repos/misode/mcmeta/git/refs/tags/1.21.1-summary Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1076:8)
    at ssl.onhandshakedone (node:_tls_wrap:862:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
[Info  - 13:32:49] [Downloader] [mc-je/1.21.1/registries.json.gz] Downloaded from https://raw.githubusercontent.com/misode/mcmeta/1.21.1-summary/registries/data.json.gz
[Info  - 13:32:49] [Profiler: project#init] Done: Initialize in 2462.3609 ms
[Info  - 13:32:49] [Profiler: project#init] == Summary ==
[Info  - 13:32:49] [Profiler: project#init] Load Cache  - 184.98870000000002 ms
[Info  - 13:32:49] [Profiler: project#init] Load Config - 4.706699999999955 ms
[Info  - 13:32:49] [Profiler: project#init] Initialize  - 2462.3609 ms
[Info  - 13:32:49] [Profiler: project#init] Total       - 2652.0563 ms
[Error - 13:32:49] [Downloader] [mc-je/1.21.1/mcmeta.tar.gz.commit-sha] Downloading https://api.github.com/repos/misode/mcmeta/git/refs/tags/1.21.1-data Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1076:8)
    at ssl.onhandshakedone (node:_tls_wrap:862:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
[Error - 13:32:49] [Downloader] [mc-je/1.21.1/mcmeta.tar.gz] Downloading https://api.github.com/repos/misode/mcmeta/tarball/refs/tags/1.21.1-data Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1076:8)
    at ssl.onhandshakedone (node:_tls_wrap:862:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
[Error - 13:32:49] [Downloader] [mc-je/1.21.1/mcmeta.tar.gz] Fallback: loading cached file file:///C:/Users/xiang/AppData/Local/spyglassmc-nodejs/Cache/downloader/mc-je/1.21.1/mcmeta.tar.gz Error: ENOENT: no such file or directory, open 'C:\Users\xiang\AppData\Local\spyglassmc-nodejs\Cache\downloader\mc-je\1.21.1\mcmeta.tar.gz'
    at async open (node:internal/fs/promises:641:25)
    at async Object.readFile (node:internal/fs/promises:1258:14)
    at async x0.download (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:393)
    at async u_ (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:112:7137)
    at async a_ (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:112:7346)
    at async t (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:14415)
    at async r (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:14758)
    at async Promise.all (index 0)
    at async i (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:15530)
    at async Eo.ready (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:16811) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\xiang\\AppData\\Local\\spyglassmc-nodejs\\Cache\\downloader\\mc-je\\1.21.1\\mcmeta.tar.gz'
}
[Info  - 13:32:49] [Project] [getDependencies] Executed provider “@vanilla-datapack”
[Error - 13:32:49] [Downloader] [mc-je/1.21.1/mcmeta-assets.tar.gz.commit-sha] Downloading https://api.github.com/repos/misode/mcmeta/git/refs/tags/1.21.1-assets-tiny Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1076:8)
    at ssl.onhandshakedone (node:_tls_wrap:862:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
[Error - 13:32:49] [Downloader] [mc-je/1.21.1/mcmeta-assets.tar.gz] Downloading https://api.github.com/repos/misode/mcmeta/tarball/refs/tags/1.21.1-assets-tiny Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1076:8)
    at ssl.onhandshakedone (node:_tls_wrap:862:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
[Error - 13:32:49] [Downloader] [mc-je/1.21.1/mcmeta-assets.tar.gz] Fallback: loading cached file file:///C:/Users/xiang/AppData/Local/spyglassmc-nodejs/Cache/downloader/mc-je/1.21.1/mcmeta-assets.tar.gz Error: ENOENT: no such file or directory, open 'C:\Users\xiang\AppData\Local\spyglassmc-nodejs\Cache\downloader\mc-je\1.21.1\mcmeta-assets.tar.gz'
    at async open (node:internal/fs/promises:641:25)
    at async Object.readFile (node:internal/fs/promises:1258:14)
    at async x0.download (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:393)
    at async u_ (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:112:7137)
    at async c_ (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:112:7529)
    at async t (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:14415)
    at async r (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:14758)
    at async Promise.all (index 0)
    at async i (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:15530)
    at async Eo.ready (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:16811) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\xiang\\AppData\\Local\\spyglassmc-nodejs\\Cache\\downloader\\mc-je\\1.21.1\\mcmeta-assets.tar.gz'
}
[Info  - 13:32:49] [Project] [getDependencies] Executed provider “@vanilla-resourcepack”
[Error - 13:32:49] [Downloader] [mc-je/vanilla-mcdoc.tar.gz.commit-sha] Downloading https://api.github.com/repos/SpyglassMC/vanilla-mcdoc/git/refs/heads/main Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1076:8)
    at ssl.onhandshakedone (node:_tls_wrap:862:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
[Error - 13:32:49] [Downloader] [mc-je/vanilla-mcdoc.tar.gz] Downloading https://api.github.com/repos/SpyglassMC/vanilla-mcdoc/tarball/refs/heads/main Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1677:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1076:8)
    at ssl.onhandshakedone (node:_tls_wrap:862:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
[Error - 13:32:49] [Downloader] [mc-je/vanilla-mcdoc.tar.gz] Fallback: loading cached file file:///C:/Users/xiang/AppData/Local/spyglassmc-nodejs/Cache/downloader/mc-je/vanilla-mcdoc.tar.gz Error: ENOENT: no such file or directory, open 'C:\Users\xiang\AppData\Local\spyglassmc-nodejs\Cache\downloader\mc-je\vanilla-mcdoc.tar.gz'
    at async open (node:internal/fs/promises:641:25)
    at async Object.readFile (node:internal/fs/promises:1258:14)
    at async x0.download (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:393)
    at async l_ (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:112:7802)
    at async t (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:14415)
    at async r (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:14758)
    at async Promise.all (index 0)
    at async i (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:15530)
    at async Eo.ready (c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:69:16811)
    at async c:\Users\xiang\.vscode\extensions\spgoding.datapack-language-server-4.4.0\dist\server.js:128:25908 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\xiang\\AppData\\Local\\spyglassmc-nodejs\\Cache\\downloader\\mc-je\\vanilla-mcdoc.tar.gz'
}
[Info  - 13:32:49] [Project] [getDependencies] Executed provider “@vanilla-mcdoc”
[Error - 13:32:49] [FileUriSupporter#create] Bad dependency file:///C:/Users/xiang/AppData/Local/spyglassmc-nodejs/Cache/downloader/mc-je/1.21.1/mcmeta.tar.gz [Error: ENOENT: no such file or directory, stat 'C:\Users\xiang\AppData\Local\spyglassmc-nodejs\Cache\downloader\mc-je\1.21.1\mcmeta.tar.gz'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\xiang\\AppData\\Local\\spyglassmc-nodejs\\Cache\\downloader\\mc-je\\1.21.1\\mcmeta.tar.gz'
}
[Error - 13:32:49] [FileUriSupporter#create] Bad dependency file:///C:/Users/xiang/AppData/Local/spyglassmc-nodejs/Cache/downloader/mc-je/1.21.1/mcmeta-assets.tar.gz [Error: ENOENT: no such file or directory, stat 'C:\Users\xiang\AppData\Local\spyglassmc-nodejs\Cache\downloader\mc-je\1.21.1\mcmeta-assets.tar.gz'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\xiang\\AppData\\Local\\spyglassmc-nodejs\\Cache\\downloader\\mc-je\\1.21.1\\mcmeta-assets.tar.gz'
}
[Error - 13:32:49] [FileUriSupporter#create] Bad dependency file:///C:/Users/xiang/AppData/Local/spyglassmc-nodejs/Cache/downloader/mc-je/vanilla-mcdoc.tar.gz [Error: ENOENT: no such file or directory, stat 'C:\Users\xiang\AppData\Local\spyglassmc-nodejs\Cache\downloader\mc-je\vanilla-mcdoc.tar.gz'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\xiang\\AppData\\Local\\spyglassmc-nodejs\\Cache\\downloader\\mc-je\\vanilla-mcdoc.tar.gz'
}
[Error - 13:32:49] [SpyglassUriSupporter#create] Bad dependency file:///C:/Users/xiang/AppData/Local/spyglassmc-nodejs/Cache/downloader/mc-je/1.21.1/mcmeta.tar.gz [Error: ENOENT: no such file or directory, stat 'C:\Users\xiang\AppData\Local\spyglassmc-nodejs\Cache\downloader\mc-je\1.21.1\mcmeta.tar.gz'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\xiang\\AppData\\Local\\spyglassmc-nodejs\\Cache\\downloader\\mc-je\\1.21.1\\mcmeta.tar.gz'
}
[Error - 13:32:49] [SpyglassUriSupporter#create] Bad dependency file:///C:/Users/xiang/AppData/Local/spyglassmc-nodejs/Cache/downloader/mc-je/1.21.1/mcmeta-assets.tar.gz [Error: ENOENT: no such file or directory, stat 'C:\Users\xiang\AppData\Local\spyglassmc-nodejs\Cache\downloader\mc-je\1.21.1\mcmeta-assets.tar.gz'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\xiang\\AppData\\Local\\spyglassmc-nodejs\\Cache\\downloader\\mc-je\\1.21.1\\mcmeta-assets.tar.gz'
}
[Error - 13:32:49] [SpyglassUriSupporter#create] Bad dependency file:///C:/Users/xiang/AppData/Local/spyglassmc-nodejs/Cache/downloader/mc-je/vanilla-mcdoc.tar.gz [Error: ENOENT: no such file or directory, stat 'C:\Users\xiang\AppData\Local\spyglassmc-nodejs\Cache\downloader\mc-je\vanilla-mcdoc.tar.gz'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\xiang\\AppData\\Local\\spyglassmc-nodejs\\Cache\\downloader\\mc-je\\vanilla-mcdoc.tar.gz'
}
[Info  - 13:32:49] [Profiler: project#ready] Done: List URIs in 368.1866 ms
[Info  - 13:32:49] [SymbolRegistrar] Skipped “mcmeta-summary” thanks to cache undefined_v3
[Info  - 13:32:49] [Profiler: project#ready] Done: Register Symbols in 0.09799999999995634 ms
[Info  - 13:32:49] [Profiler: project#ready] Done: Pop Errors in 1.3150000000000546 ms
[Info  - 13:32:49] [Profiler: project#ready] Done: Validate Cache in 214.60460000000012 ms
[Info  - 13:32:49] [Profiler: project#ready] Done: Bind URIs in 0.03199999999969805 ms
[Info  - 13:32:49] [Profiler: project#ready] Done: Sort URIs in 0.06480000000010477 ms
[Info  - 13:32:49] [Profiler: project#ready#bind] == Summary ==
[Info  - 13:32:49] [Profiler: project#ready#bind] Total tasks: 2 done in 4.434600000000046 ms
[Info  - 13:32:49] [Profiler: project#ready#bind] Min/Avg/Max: 0.8337000000001353 / 2.217300000000023 / 3.6008999999999105 ms
[Info  - 13:32:49] [Profiler: project#ready#bind] Top 2 task(s):
[Info  - 13:32:49] [Profiler: project#ready#bind] file:///d:/GitHub%20Desktop/datapackets-functions-LIB/pack.png - 3.6008999999999105 ms (81.20010823974819%)
[Info  - 13:32:49] [Profiler: project#ready#bind] file:///d:/GitHub%20Desktop/SetBlock-TNT/pack.png              - 0.8337000000001353 ms (18.799891760251807%)
[Info  - 13:32:49] [Profiler: project#ready] Done: Bind Files in 4.678699999999935 ms
[Info  - 13:32:49] [Profiler: project#ready] == Summary ==
[Info  - 13:32:49] [Profiler: project#ready] List URIs        - 368.1866 ms
[Info  - 13:32:49] [Profiler: project#ready] Register Symbols - 0.09799999999995634 ms
[Info  - 13:32:49] [Profiler: project#ready] Pop Errors       - 1.3150000000000546 ms
[Info  - 13:32:49] [Profiler: project#ready] Validate Cache   - 214.60460000000012 ms
[Info  - 13:32:49] [Profiler: project#ready] Bind URIs        - 0.03199999999969805 ms
[Info  - 13:32:49] [Profiler: project#ready] Sort URIs        - 0.06480000000010477 ms
[Info  - 13:32:49] [Profiler: project#ready] Bind Files       - 4.678699999999935 ms
[Info  - 13:32:49] [Profiler: project#ready] Total            - 588.9796999999999 ms
[Warn  - 13:32:52] Tried to access unknown reference ::java::server::util::text::Text
[Warn  - 13:32:52] Tried to access unknown reference ::java::server::util::text::Text
[Warn  - 13:32:52] Tried to access unknown reference ::java::server::util::text::Text
[Warn  - 13:32:52] Tried to access unknown reference ::java::server::util::text::Text
[Warn  - 13:32:52] Tried to access unknown reference ::java::server::util::text::Text
[Warn  - 13:32:52] Tried to access unknown reference ::java::server::util::text::Text

**Comment by WhiteElephant-abc** [comment]
![Image](https://github.com/user-attachments/assets/144eab3e-153f-484a-9284-f48166f04369)
These are all the plugins I use.

**Comment by misode** [comment]
Thank you. Looking at the log, it seems like `api.github.com` might be blocked in your country (or there might be another neteork/firewall issue). Try enabling a VPN if you are able to.

In the future we are planning to create a proxy for this, since it seems like a common problem.
- See #1480

**Comment by WhiteElephant-abc** [comment]
It was automatically fixed after I installed the Code Spell Checker plugin.
